### PR TITLE
Bug/571

### LINKED ISSUE #571: Casandra source Mapping tinyint to short(should be byte)
I am using  source connector to  push my data from cassandra   table to kafka topic but for the the column of data type tinyint it is try to convert it into short and i am getting excetption 

=> org.apache.kafka.connect.errors.ConnectException: Connector msg-connector error processing row Row[6181, 12084, 5341, NULL, NULL, NULL, {"cardType":"BASIC_CARD","cardId":null,"msgText":"uuqieybqibdi2w","msgContentType":"TEXT","msgAttachmentUrl":null,"caption":null}, 0, NULL, 0, Tue Apr 09 16:06:50 IST 2019, NULL, 1232433602057, NULL, 0, false, NULL, 3, NULL, 7, NULL, NULL, NULL, NULL, 1, 3, Tue Apr 09 16:06:50 IST 2019] for table chat_inbox.chat_message.
at com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader$$anonfun$process$1.applyOrElse(CassandraTableReader.scala:247)
at com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader$$anonfun$process$1.applyOrElse(CassandraTableReader.scala:215)
at scala.concurrent.Future$$anonfun$onSuccess$1.apply(Future.scala:119)
at scala.concurrent.Future$$anonfun$onSuccess$1.apply(Future.scala:117)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: com.datastax.driver.core.exceptions.CodecNotFoundException: Codec not found for requested operation: [tinyint <-> java.lang.Short]

I checked yoursouce code and found this  line -> 
case DataType.Name.TINYINT | DataType.Name.SMALLINT => row.getShort(columnDef.getName)

expected => tinyint should be mapped to byte and small int to short

### PR DESCRIPTION
**Pull request by andrewstevenson**
Fixes #571

---
This change is [Reviewable](https://reviewable.io/reviews/landoop/stream-reactor/588)

### CODE REVIEW

File: kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CassandraTypeConverter.scala [hunk 1]
```diff
@@ -38,9 +38,9 @@ class CassandraTypeConverter(private val codecRegistry: CodecRegistry,
                              private val setting: CassandraSourceSetting) extends StrictLogging {
 
   val mapper = new ObjectMapper()
-  val OPTIONAL_DATE_SCHEMA = org.apache.kafka.connect.data.Date.builder().optional().build()
-  val OPTIONAL_TIMESTAMP_SCHEMA = Timestamp.builder().optional().build()
-  val OPTIONAL_DECIMAL_SCHEMA = Decimal.builder(18).optional().build()
+  val OPTIONAL_DATE_SCHEMA: Schema = org.apache.kafka.connect.data.Date.builder().optional().build()
```
Comment (spirosoik) [inline kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CassandraTypeConverter.scala]: why did we add it back? we have the type inference

Comment (andrewstevenson) [reply kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CassandraTypeConverter.scala]: Type annotations for public member is the standard.
